export const blogPosts = [
  {
    id: "1",
    title: "The Future of Web Development: Trends to Watch",
    thumbnail: "https://example.com/thumbnails/webdev.jpg",
    description:
      "Explore the top web development trends that are shaping the future of digital experiences.",
    author: "Jane Doe",
    tags: ["Web Development", "Trends", "Technology"],
    views: 1024,
    comments: 12,
    likes: 230,
    dislikes: 15,
  },
  {
    id: "2",
    title: "10 JavaScript Frameworks You Should Know in 2024",
    thumbnail: "https://example.com/thumbnails/js-frameworks.jpg",
    description:
      "A breakdown of the most popular JavaScript frameworks and how they can enhance your projects.",
    author: "John Smith",
    tags: ["JavaScript", "Frameworks", "Development"],
    views: 2980,
    comments: 30,
    likes: 540,
    dislikes: 8,
  },
  {
    id: "3",
    title: "How to Create a Personal Blog Using Next.js",
    thumbnail: "https://example.com/thumbnails/nextjs-blog.jpg",
    description:
      "Step-by-step guide on building a blog with Next.js, from setup to deployment.",
    author: "Alex Johnson",
    tags: ["Next.js", "Tutorial", "Blog"],
    views: 1650,
    comments: 18,
    likes: 450,
    dislikes: 22,
  },
  {
    id: "4",
    title: "Why Dark Mode is More Than Just a Trend",
    thumbnail: "https://example.com/thumbnails/dark-mode.jpg",
    description:
      "Learn about the benefits of dark mode and why it's becoming a standard in UI design.",
    author: "Emily Davis",
    tags: ["UI Design", "Dark Mode", "UX"],
    views: 845,
    comments: 7,
    likes: 200,
    dislikes: 3,
  },
  {
    id: "5",
    title: "Mastering Tailwind CSS: Tips and Tricks",
    thumbnail: "https://example.com/thumbnails/tailwind-css.jpg",
    description:
      "A comprehensive guide to optimizing your workflow with Tailwind CSS.",
    author: "Michael Lee",
    tags: ["Tailwind CSS", "CSS", "Design"],
    views: 1902,
    comments: 24,
    likes: 300,
    dislikes: 11,
  },
  {
    id: "6",
    title: "How Artificial Intelligence is Revolutionizing Content Creation",
    thumbnail: "https://example.com/thumbnails/ai-content.jpg",
    description:
      "Discover how AI tools are changing the landscape of content creation and automation.",
    author: "Sophia Martinez",
    tags: ["AI", "Content Creation", "Automation"],
    views: 1240,
    comments: 16,
    likes: 370,
    dislikes: 5,
  },
  {
    id: "7",
    title: "SEO Best Practices for 2024: What You Need to Know",
    thumbnail: "https://example.com/thumbnails/seo-2024.jpg",
    description:
      "Stay ahead of the competition with these SEO tips and tricks for the coming year.",
    author: "James Brown",
    tags: ["SEO", "Marketing", "2024"],
    views: 2154,
    comments: 33,
    likes: 620,
    dislikes: 19,
  },
  {
    id: "8",
    title: "Understanding Progressive Web Apps (PWAs): The Future of Mobile",
    thumbnail: "https://example.com/thumbnails/pwa.jpg",
    description:
      "Learn why PWAs are gaining traction and how they compare to native mobile apps.",
    author: "Rachel Green",
    tags: ["PWA", "Mobile", "Development"],
    views: 960,
    comments: 9,
    likes: 180,
    dislikes: 7,
  },
  {
    id: "9",
    title: "Top 5 Productivity Tools for Remote Developers",
    thumbnail: "https://example.com/thumbnails/productivity-tools.jpg",
    description:
      "Boost your productivity with these must-have tools for remote development.",
    author: "Tom Wilson",
    tags: ["Productivity", "Remote Work", "Tools"],
    views: 1425,
    comments: 20,
    likes: 325,
    dislikes: 14,
  },
  {
    id: "10",
    title: "A Guide to Building Accessible Websites",
    thumbnail: "https://example.com/thumbnails/accessible-web.jpg",
    description:
      "Ensure your website is accessible to everyone with this comprehensive guide to web accessibility.",
    author: "Anna Taylor",
    tags: ["Accessibility", "Web Design", "Inclusivity"],
    views: 1340,
    comments: 14,
    likes: 295,
    dislikes: 9,
  },
];
