"use server";

const author = {
  firstName: "Samuel",
  lastName: "Samuel",
  avatar: null,
};

const blogPosts = [
  {
    id: "1",
    title: "The Future of Web Development: Trends to Watch",
    thumbnail: null,
    description:
      "Explore the top web development trends that are shaping the future of digital experiences.",
    author,
    tags: [
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
      "Web Development",
      "Trends",
      "Technology",
    ],
    views: 1024,
    comments: 12,
    likes: 230,
    dislikes: 15,
  },
  {
    id: "2",
    title: "10 JavaScript Frameworks You Should Know in 2024",
    thumbnail: null,
    description:
      "ost popular JavaScript frameworks and how they can enhance your projects.",
    author,
    tags: ["JavaScript", "Frameworks", "Development"],
    views: 2980,
    comments: 30,
    likes: 540,
    dislikes: 8,
  },
  {
    id: "3",
    title: "How to Create a Personal Blog Using Next.js",
    thumbnail: null,
    description:
      "Step-by-step guide on building a blog with Next.js, from setup to deployment.",
    author,
    tags: ["Next.js", "Tutorial", "Blog"],
    views: 1650,
    comments: 18,
    likes: 450,
    dislikes: 22,
  },
  {
    id: "4",
    title: "Why Dark Mode is More Than Just a Trend",
    thumbnail: null,
    description:
      "Learn about the benefits of dark mode and why it's becoming a standard in UI design.",
    author,
    tags: ["UI Design", "Dark Mode", "UX"],
    views: 845,
    comments: 7,
    likes: 200,
    dislikes: 3,
  },
  {
    id: "5",
    title: "Mastering Tailwind CSS: Tips and Tricks",
    thumbnail: null,
    description:
      "A comprehensive guide to optimizing your workflow with Tailwind CSS.",
    author,
    tags: ["Tailwind CSS", "CSS", "Design"],
    views: 1902,
    comments: 24,
    likes: 300,
    dislikes: 11,
  },
  {
    id: "6",
    title: "How Artificial Intelligence is Revolutionizing Content Creation",
    thumbnail: null,
    description:
      "Discover how AI tools are changing the landscape of content creation and automation.",
    author,
    tags: ["AI", "Content Creation", "Automation"],
    views: 1240,
    comments: 16,
    likes: 370,
    dislikes: 5,
  },
  {
    id: "7",
    title: "SEO Best Practices for 2024: What You Need to Know",
    thumbnail: null,
    description:
      "Stay ahead of the competition with these SEO tips and tricks for the coming year.",
    author,
    tags: ["SEO", "Marketing", "2024"],
    views: 2154,
    comments: 33,
    likes: 620,
    dislikes: 19,
  },
  {
    id: "8",
    title: "Understanding Progressive Web Apps (PWAs): The Future of Mobile",
    thumbnail: null,
    description:
      "Learn why PWAs are gaining traction and how they compare to native mobile apps.",
    author,
    tags: ["PWA", "Mobile", "Development"],
    views: 960,
    comments: 9,
    likes: 180,
    dislikes: 7,
  },
  {
    id: "9",
    title: "Top 5 Productivity Tools for Remote Developers",
    thumbnail: null,
    description:
      "Boost your productivity with these must-have tools for remote development.",
    author,
    tags: ["Productivity", "Remote Work", "Tools"],
    views: 1425,
    comments: 20,
    likes: 325,
    dislikes: 14,
  },
  {
    id: "10",
    title: "A Guide to Building Accessible Websites",
    thumbnail: null,
    description:
      "Ensure your website is accessible to everyone with this comprehensive guide to web accessibility.",
    author,
    tags: ["Accessibility", "Web Design", "Inclusivity"],
    views: 1340,
    comments: 14,
    likes: 295,
    dislikes: 9,
  },
];

export const getPosts = async () => {
  return blogPosts;
};
